## import des fichiers avec pandas

In [ ]:
import pandas as pd

df_erp=pd.read_excel("data/Fichier_erp.xlsx")
df_cms=pd.read_excel("data/Fichier_web.xlsx")
df_liaison=pd.read_excel("data/fichier_liaison.xlsx")

c:\Users\Utilisateur\.pyenv\pyenv-win\versions\3.13.1\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

## check des fichiers, voir le nombre de lignes et de colonnes

In [30]:
print("ERP :", df_erp.shape)
print("CMS :", df_cms.shape)
print("Liaison :", df_liaison.shape)

ERP : (825, 5)
CMS : (1513, 28)
Liaison : (825, 2)

## check du noms des colonnes des fichiers, pour voir ce que les colonnes stockent

In [31]:
print("Colonnes ERP :", df_erp.columns.tolist())
print("Colonnes CMS :", df_cms.columns.tolist())
print("Colonnes liaison :", df_liaison.columns.tolist())

Colonnes ERP : ['product_id', 'onsale_web', 'price', 'stock_quantity', 'stock_status']
Colonnes CMS : ['sku', 'virtual', 'downloadable', 'rating_count', 'average_rating', 'total_sales', 'tax_status', 'tax_class', 'post_author', 'post_date', 'post_date_gmt', 'post_content', 'post_title', 'post_excerpt', 'post_status', 'comment_status', 'ping_status', 'post_password', 'post_name', 'post_modified', 'post_modified_gmt', 'post_content_filtered', 'post_parent', 'guid', 'menu_order', 'post_type', 'post_mime_type', 'comment_count']
Colonnes liaison : ['product_id', 'id_web']

## check des types de chaque colonnes

In [32]:
print("Types ERP :")
print(df_erp.dtypes)

print("\nTypes CMS :")
print(df_cms.dtypes)

print("\nTypes liaison :")
print(df_liaison.dtypes)

Types ERP :
product_id          int64
onsale_web          int64
price             float64
stock_quantity      int64
stock_status          str
dtype: object

Types CMS :
sku                              object
virtual                           int64
downloadable                      int64
rating_count                      int64
average_rating                  float64
total_sales                     float64
tax_status                          str
tax_class                       float64
post_author                     float64
post_date                datetime64[us]
post_date_gmt            datetime64[us]
post_content                    float64
post_title                          str
post_excerpt                        str
post_status                         str
comment_status                      str
ping_status                         str
post_password                   float64
post_name                           str
post_modified            datetime64[us]
post_modified_gmt        datetime64[us]
post_content_filtered           float64
post_parent                     float64
guid                                str
menu_order                      float64
post_type                           str
post_mime_type                      str
comment_count                   float64
dtype: object

Types liaison :
product_id     int64
id_web        object
dtype: object

## affichage d'un aperçu des données avec la fonction head()

In [35]:
print("ERP")
display(df_erp.head())

print("CMS")
display(df_cms.head())

print("Liaison")
display(df_liaison.head())

ERP

   product_id  onsale_web  price  stock_quantity stock_status
0        3847           1   24.2               0   outofstock
1        3849           1   34.3               0   outofstock
2        3850           1   20.8               0   outofstock
3        4032           1   14.1               0   outofstock
4        4039           1   46.0               0   outofstock

CMS

,sku,virtual,downloadable,rating_count,average_rating,total_sales,tax_status,tax_class,post_author,post_date,...,post_name,post_modified,post_modified_gmt,post_content_filtered,post_parent,guid,menu_order,post_type,post_mime_type,comment_count
0,16004,0,0,0,0.0,5.0,NaN,NaN,2.0,2018-06-07 16:27:25,...,chateau-du-couvent-pomerol-2017,2020-08-25 18:35:02,2020-08-25 16:35:02,NaN,0.0,https://www.bottle-neck.fr/wp-content/uploads/...,0.0,attachment,image/jpeg,0.0
1,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaT,...,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,15075,0,0,0,0.0,3.0,taxable,NaN,2.0,2018-02-14 15:39:43,...,pares-balta-penedes-indigena-2017,2020-08-20 15:35:02,2020-08-20 13:35:02,NaN,0.0,https://www.bottle-neck.fr/?post_type=product&...,0.0,product,NaN,0.0
3,16209,0,0,0,0.0,6.0,taxable,NaN,2.0,2018-02-14 17:15:31,...,maurel-cabardes-tradition-2017,2020-08-05 18:05:03,2020-08-05 16:05:03,NaN,0.0,https://www.bottle-neck.fr/?post_type=product&...,0.0,product,NaN,0.0
4,15763,0,0,0,0.0,1.0,NaN,NaN,2.0,2020-01-25 14:08:16,...,domaine-de-la-monardiere-vacqueyras-les-vieill...,2020-08-21 11:35:02,2020-08-21 09:35:02,NaN,0.0,https://www.bottle-neck.fr/wp-content/uploads/...,0.0,attachment,image/jpeg,0.0

Liaison

   product_id id_web
0        3847  15298
1        3849  15296
2        3850  15300
3        4032  19814
4        4039  19815

## vérification des valeurs manquantes dans le jeu de données

In [36]:
print("Valeurs manquantes ERP")
display(df_erp.isna().sum())

print("Valeurs manquantes CMS")
display(df_cms.isna().sum())

print("Valeurs manquantes liaison")
display(df_liaison.isna().sum())

Valeurs manquantes ERP

product_id        0
onsale_web        0
price             0
stock_quantity    0
stock_status      0
dtype: int64

Valeurs manquantes CMS

sku                        85
virtual                     0
downloadable                0
rating_count                0
average_rating             83
total_sales                83
tax_status                797
tax_class                1513
post_author                83
post_date                  83
post_date_gmt              83
post_content             1513
post_title                 83
post_excerpt              797
post_status                83
comment_status             83
ping_status                83
post_password            1513
post_name                  83
post_modified              83
post_modified_gmt          83
post_content_filtered    1513
post_parent                83
guid                       83
menu_order                 83
post_type                  83
post_mime_type            799
comment_count              83
dtype: int64

Valeurs manquantes liaison

product_id     0
id_web        91
dtype: int64

## on continue l'exploration en regardant les doublons

In [37]:
print("Doublons complets ERP :", df_erp.duplicated().sum())
print("Doublons complets CMS :", df_cms.duplicated().sum())
print("Doublons complets liaison :", df_liaison.duplicated().sum())

Doublons complets ERP : 0
Doublons complets CMS : 82
Doublons complets liaison : 0

## check de l'unicité

In [38]:
print("ERP - product_id uniques :", df_erp["product_id"].nunique())
print("ERP - nombre de lignes :", len(df_erp))

print("CMS - sku uniques :", df_cms["sku"].nunique())
print("CMS - nombre de lignes :", len(df_cms))

print("Liaison - product_id uniques :", df_liaison["product_id"].nunique())
print("Liaison - id_web uniques :", df_liaison["id_web"].nunique())
print("Liaison - nombre de lignes :", len(df_liaison))

ERP - product_id uniques : 825
ERP - nombre de lignes : 825
CMS - sku uniques : 714
CMS - nombre de lignes : 1513
Liaison - product_id uniques : 825
Liaison - id_web uniques : 734
Liaison - nombre de lignes : 825

## doublons mais sur les clés principalement

In [43]:
print(
    "ERP - doublons product_id :",
    df_erp["product_id"].dropna().duplicated().sum()
)

print(
    "CMS - doublons sku :",
    df_cms["sku"].dropna().duplicated().sum()
)

print(
    "Liaison - doublons product_id :",
    df_liaison["product_id"].dropna().duplicated().sum()
)

print(
    "Liaison - doublons id_web :",
    df_liaison["id_web"].dropna().duplicated().sum()
)

ERP - doublons product_id : 0
CMS - doublons sku : 714
Liaison - doublons product_id : 0
Liaison - doublons id_web : 0

# Synthese de la carto

## ERP

- Volumétrie : **825 lignes et 5 colonnes**.
- Clé probable : `product_id`.
- `product_id` contient **825 valeurs uniques pour 825 lignes**.
- Aucune valeur manquante n'est présente dans le fichier.
- Aucun doublon complet n'a été détecté.
- Aucun doublon n'a été détecté sur `product_id`.
- `product_id` peut donc être considéré comme une **clé candidate**.
- Les données contiennent notamment le prix, le stock et le statut du stock.

## CMS / Web

- Volumétrie : **1 513 lignes et 28 colonnes**.
- Clé probable : `sku`.
- `sku` contient **714 valeurs uniques**.
- **85 valeurs de `sku` sont manquantes**.
- Après exclusion des valeurs manquantes, **714 doublons sont présents sur `sku`**.
- **82 doublons complets** sont également présents dans le fichier.
- Plusieurs autres colonnes contiennent des valeurs manquantes.
- La colonne `sku` n'est donc pas unique dans le fichier brut et devra être nettoyée avant la jointure.

## Fichier de liaison

- Volumétrie : **825 lignes et 2 colonnes**.
- Colonnes de liaison : `product_id` et `id_web`.
- `product_id` contient **825 valeurs uniques**, sans valeur manquante ni doublon.
- `id_web` contient **734 valeurs uniques** et **91 valeurs manquantes**.
- Parmi les `id_web` renseignés, aucun doublon n'a été détecté.
- Aucun doublon complet n'a été détecté dans le fichier.

## Contraintes identifiées

- Les trois sources sont fournies au format Excel `.xlsx`.
- L'ERP utilise `product_id` comme identifiant.
- Le CMS utilise `sku` comme identifiant.
- Le fichier de liaison permet de relier `product_id` à `id_web`.
- `product_id` est de type entier dans l'ERP et dans le fichier de liaison.
- `sku` et `id_web` sont de type texte / `object`.
- Le principal problème de qualité concerne le CMS : valeurs manquantes et répétitions de `sku`.
- Le fichier de liaison contient également des valeurs manquantes dans `id_web`.
- Ces problèmes devront être traités avant les jointures afin d'éviter des données manquantes ou dupliquées.

## Conclusion

L'ERP présente une structure propre avec un `product_id` unique et complet.
Le CMS nécessite un nettoyage avant utilisation, notamment à cause des `sku` manquants et non uniques.

Le fichier de liaison permet de faire le lien entre les identifiants ERP et Web, mais certaines valeurs `id_web` sont absentes.